apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodetrial-deployment
  labels:
    app: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
      - name: nodeserver
        image: additlabs/userservice:master
        ports:
        - containerPort: 3000
