apiVersion: v1
kind: Service
metadata:
  name: nodetrial-deployment
spec:
  selector:
    app: userservice
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
    nodePort: 31115
