name: Docker Build Deploy
on:
  push:
    branches: [master]
  workflow_dispatch:
env:
  REGISTRY: docker.io
  GITREPO: ${{secrets.DOCKERHUB_REPO_NAME }}
  IMAGE_NAME: ${{secrets.DOCKERHUB_USERNAME }}
  DOCKERUSER: ${{secrets.DOCKERHUB_USERNAME }}
  DOCKERPASSWORD: ${{secrets.DOCKERHUB_PASSWORD }}
  PROJECTID: ${{secrets.GCP_PROJECT_ID }}
  CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  CLUSTERNAME: ${{secrets.KUBE_CLUSTER_NAME }}
  CLUSTERZONE: ${{secrets.KUBE_CLUSTER_ZONE }}
jobs:
  create-user-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ env.DOCKERUSER }}
        password: ${{ env.DOCKERPASSWORD }}

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v1

    - name: Extract Docker metadata
      id: meta
      uses: docker/metadata-action@v2
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ env.GITREPO }}

    - name: Build and Push Versioned Docker Image
      id: build-and-push
      uses: docker/build-push-action@v2
      if: ${{ github.ref != 'refs/heads/main' }}
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  deployment:
    needs: [create-user-image]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: kubectl - Google Cloud GKE cluster.
      uses: ameydev/gke-kubectl-action@master
      env:
        PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        CLUSTER_NAME: ${{ secrets.KUBE_CLUSTER_NAME }}
        ZONE_NAME: ${{secrets.KUBE_CLUSTER_ZONE }}
      with:
        args: apply -f k8s/
